apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kiro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kiro/backend
        env:
        - name: DATABASE_URL
          value: postgres://kiro:password@postgres:5432/kiro
        - name: REDIS_URL
          value: redis://redis:6379
        - name: JWT_SECRET
          value: dev_jwt_secret_change_in_production
        - name: RUST_LOG
          value: debug
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kiro-dev
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000