apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kiro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kiro/frontend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kiro-dev
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5000