[package]
name = "music-streaming-blocklist-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Minimal dependencies for Rust 1.69
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
uuid = { version = "1.3", features = ["v4", "serde"] }
tokio = { version = "1.15", features = ["full"] }
futures = "0.3.21"
thiserror = "1.0.30"
anyhow = "1.0.57"
dashmap = "5.2"
levenshtein = "1.0"
reqwest = { version = "0.11.14", features = ["json"] }
urlencoding = "2.1"

[dev-dependencies]
# Removed wiremock due to Rust version compatibility
# wiremock = "0.5"
tokio-test = "0.4"