[package]
name = "music-streaming-blocklist-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework - using older stable versions
warp = "0.3"
tokio = { version = "1.20", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUID and time
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Environment
dotenv = "0.15"

# Error handling
anyhow = "1.0"

# Logging
env_logger = "0.10"
log = "0.4"