{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kiro.fullname" . }}-config
  labels:
    {{- include "kiro.labels" . | nindent 4 }}
data:
  RUST_LOG: {{ .Values.backend.env.RUST_LOG | quote }}
  TOTP_ISSUER: {{ .Values.backend.env.TOTP_ISSUER | quote }}
{{- end }}