{{- if .Values.backend.duckdb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ndith.fullname" . }}-duckdb
  labels:
    {{- include "ndith.backend.labels" . | nindent 4 }}
    component: analytics-storage
spec:
  accessModes:
    {{- range .Values.backend.duckdb.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.duckdb.persistence.size | quote }}
  {{- if .Values.backend.duckdb.persistence.storageClass }}
  storageClassName: {{ .Values.backend.duckdb.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
