apiVersion: v1
kind: ConfigMap
metadata:
  name: kiro-config
  namespace: kiro-production
data:
  RUST_LOG: "info"
  DATABASE_MAX_CONNECTIONS: "20"
  REDIS_MAX_CONNECTIONS: "10"
  RATE_LIMIT_WINDOW: "3600"
  ENFORCEMENT_BATCH_SIZE: "50"
  TOKEN_ROTATION_INTERVAL: "86400"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"