apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-blocklist-api
  namespace: music-blocklist-dev
  labels:
    app: music-blocklist-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-blocklist-api
  template:
    metadata:
      labels:
        app: music-blocklist-api
        version: v1
    spec:
      containers:
      - name: api
        image: music-blocklist/api:dev
        imagePullPolicy: Never  # Use local images in minikube
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: JWT_SECRET
        - name: KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: KMS_KEY_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: SPOTIFY_CLIENT_SECRET
        - name: APPLE_MUSIC_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: APPLE_MUSIC_PRIVATE_KEY
        envFrom:
        - configMapRef:
            name: music-blocklist-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: music-blocklist-api
  namespace: music-blocklist-dev
  labels:
    app: music-blocklist-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    name: http
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    name: metrics
  selector:
    app: music-blocklist-api