apiVersion: v1
kind: ConfigMap
metadata:
  name: music-blocklist-config
  namespace: music-blocklist-dev
data:
  RUST_LOG: "debug"
  DATABASE_MAX_CONNECTIONS: "10"
  REDIS_MAX_CONNECTIONS: "5"
  RATE_LIMIT_WINDOW: "3600"
  ENFORCEMENT_BATCH_SIZE: "25"
  TOKEN_ROTATION_INTERVAL: "86400"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: music-blocklist-dev
data:
  init.sql: |
    -- Initialize database with required extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_trgm";
    
    -- Create indexes for text search
    -- These will be created by migrations, but having them here ensures they exist