apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: music-blocklist-dev
  labels:
    app: database-migration
spec:
  template:
    metadata:
      labels:
        app: database-migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: music-blocklist/migration:dev
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: music-blocklist-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"