apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-blocklist-frontend
  namespace: music-blocklist-dev
  labels:
    app: music-blocklist-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-blocklist-frontend
  template:
    metadata:
      labels:
        app: music-blocklist-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: music-blocklist/frontend:dev
        imagePullPolicy: Never  # Use local images in minikube
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: music-blocklist-frontend
  namespace: music-blocklist-dev
  labels:
    app: music-blocklist-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    name: http
  selector:
    app: music-blocklist-frontend