# Development-specific values for kiro
# Override default values for local development

backend:
  image:
    repository: kiro/backend
    tag: latest
    pullPolicy: Never  # Use local images
  
  env:
    DATABASE_URL: "postgres://kiro:password@kiro-postgresql:5432/kiro"
    REDIS_URL: "redis://kiro-redis-master:6379"
    JWT_SECRET: "dev_jwt_secret_change_in_production"
    RUST_LOG: "debug"
    TOTP_ISSUER: "No Drake in the House (Dev)"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

frontend:
  image:
    repository: kiro/frontend
    tag: latest
    pullPolicy: Never  # Use local images
  
  env:
    VITE_API_URL: "http://localhost:3000"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

postgresql:
  enabled: true
  auth:
    username: kiro
    password: password
    database: kiro
  primary:
    persistence:
      enabled: false  # Use ephemeral storage for dev
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false  # Use ephemeral storage for dev
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "100m"

# Enable ingress for local development
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: kiro.local
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend